# Generated by Django 3.2.4 on 2021-06-14 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('univer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chair',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='group',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='student',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='university',
            name='created_at',
        ),
    ]
